In [11]:
#!pip install librosa

In [150]:
import matplotlib.pyplot as plt
%matplotlib inline
import IPython.display as ipd
import librosa
import librosa.display
#### Extracting MFCC's For every audio file
import pandas as pd
import os

In [151]:
audio_dataset_path = r'C:\Users\HP\Desktop\baby_crying\donateacry_corpus_cleaned_and_updated_data\hungry'
librosa_audio_data,librosa_sample_rate=librosa.load(audio_file_path)


In [152]:
def features_extractor(file):
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features


In [153]:
import os
import numpy as np
from tqdm import tqdm

# Define the path to your audio dataset
audio_dataset_path = r'C:\Users\HP\Desktop\baby_crying\donateacry_corpus_cleaned_and_updated_data'

# Initialize an empty list to store extracted features and labels
extracted_features = []

# Function to extract features from an audio file (placeholder)
def features_extractor(file_name):
    # Replace with your actual feature extraction code
    y, sr = librosa.load(file_name, sr=None)
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    return np.mean(mfccs.T, axis=0)

# Iterate through each folder (label) and file
for label in os.listdir(audio_dataset_path):
    folder_path = os.path.join(audio_dataset_path, label)
    if os.path.isdir(folder_path):
        for audio_file in tqdm(os.listdir(folder_path)):
            file_path = os.path.join(folder_path, audio_file)
            if file_path.endswith('.wav'):  # Ensure it's an audio file
                data = features_extractor(file_path)
                extracted_features.append([data, label])

# Convert extracted features and labels to a DataFrame if needed
import pandas as pd

features_df = pd.DataFrame(extracted_features, columns=['feature', 'class'])

# Print the DataFrame or save it to a CSV file
print(features_df)
# features_df.to_csv('extracted_features.csv', index=False)


100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 68.90it/s]

                                               feature       class
0    [-405.876, 27.121643, -42.248203, -0.3469377, ...  belly_pain
1    [-383.83685, 38.426846, -19.573414, -8.295806,...  belly_pain
2    [-304.17505, 41.778366, -26.64577, -17.834064,...  belly_pain
3    [-252.53748, 35.876537, -35.229088, -20.087471...  belly_pain
4    [-171.50912, 41.75074, -15.136598, -21.78959, ...  belly_pain
..                                                 ...         ...
452  [-457.82492, -2.3358393, -21.825369, 20.692574...       tired
453  [-299.7658, -22.056196, -54.869995, -10.684994...       tired
454  [-212.82039, -33.9803, -79.00461, -15.763538, ...       tired
455  [-181.16437, -24.079264, -38.59076, -25.037159...       tired
456  [-518.13745, 55.82258, 19.839031, 15.108027, 2...       tired

[457 rows x 2 columns]


In [181]:
features_df

feature       class
0    [-405.876, 27.121643, -42.248203, -0.3469377, ...  belly_pain
1    [-383.83685, 38.426846, -19.573414, -8.295806,...  belly_pain
2    [-304.17505, 41.778366, -26.64577, -17.834064,...  belly_pain
3    [-252.53748, 35.876537, -35.229088, -20.087471...  belly_pain
4    [-171.50912, 41.75074, -15.136598, -21.78959, ...  belly_pain
..                                                 ...         ...
452  [-457.82492, -2.3358393, -21.825369, 20.692574...       tired
453  [-299.7658, -22.056196, -54.869995, -10.684994...       tired
454  [-212.82039, -33.9803, -79.00461, -15.763538, ...       tired
455  [-181.16437, -24.079264, -38.59076, -25.037159...       tired
456  [-518.13745, 55.82258, 19.839031, 15.108027, 2...       tired

[457 rows x 2 columns]

In [182]:
### Split the dataset into independent and dependent dataset
X=np.array(features_df['feature'].tolist())
y=np.array(features_df['class'].tolist())

In [183]:
X.shape

(457, 13)

In [184]:
y

array(['belly_pain', 'belly_pain', 'belly_pain', 'belly_pain',
       'belly_pain', 'belly_pain', 'belly_pain', 'belly_pain',
       'belly_pain', 'belly_pain', 'belly_pain', 'belly_pain',
       'belly_pain', 'belly_pain', 'belly_pain', 'belly_pain', 'burping',
       'burping', 'burping', 'burping', 'burping', 'burping', 'burping',
       'burping', 'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'discomfort',
       'discomfort', 'discomfort', 'discomfort', 'hungry', 'hungry',
       'hungry', 'hungry', 'hungry', 'hungry', 'hungry', 'hungry',
       'hungry', 'hungry', 'hungry', 'hungry', 'hungry', 'hungry',
       'hungry', 'hungry', 'hungry', 'hungry', 'hungry', 'hungry',
     

In [185]:
### Label Encoder
import pickle

In [186]:
#!pip install tensorflow
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))

In [187]:
np.save('label_classes.npy', labelencoder.classes_)

In [188]:
# Save classes to a pickle file
with open('label_classes.pkl', 'wb') as file:
    pickle.dump(labelencoder.classes_, file)

In [189]:
y

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [190]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [191]:
X_train

array([[-9.8614853e+01,  1.4083795e+02,  3.6772716e+00, ...,
        -9.1676836e+00, -8.6280746e+00, -1.1213494e+01],
       [-2.3790605e+02,  3.6274277e+01, -6.8085541e+01, ...,
        -1.0337540e+01,  1.5205305e+01,  1.3561142e+01],
       [-1.1341600e+02, -1.7937687e+01, -5.2245979e+01, ...,
        -1.2297320e+01,  7.0339804e+00,  6.8785353e+00],
       ...,
       [-3.0176901e+02,  4.2159557e+00, -1.4924260e+01, ...,
        -4.6433110e+00, -2.2544725e+00, -4.5861474e-01],
       [-2.0864082e+02, -2.8164577e+01, -5.9126392e+01, ...,
        -3.4985397e+00,  1.6541507e+00, -7.9785980e-02],
       [-2.0229742e+02, -1.0486810e+01, -5.2694508e+01, ...,
        -2.8961947e+00,  7.7617645e+00,  2.7590129e+00]], dtype=float32)

In [192]:
y

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [193]:
X_train.shape

(365, 13)

In [194]:
X_test.shape

(92, 13)

In [195]:
y_train.shape

(365, 5)

In [196]:
y_test.shape

(92, 5)

In [197]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [198]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [199]:
### No of classes
num_labels=y.shape[1]

In [200]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(13,), activation='relu'))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [201]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                     │ (None, 100)                 │           1,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_20 (Activation)           │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_15 (Dropout)                 │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 200)                 │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_21 (Activation)           │ (None, 200)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_16 (Dropout)                 │ (None, 200)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 100)                 │          20,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_22 (Activation)           │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_17 (Dropout)                 │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 5)                   │             505 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_23 (Activation)           │ (None, 5)                   │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 42,205 (164.86 KB)

 Trainable params: 42,205 (164.86 KB)

 Non-trainable params: 0 (0.00 B)

In [202]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [203]:
## Trianing my model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.keras', 
                               verbose=1, save_best_only=True)
# Save the model
model.save('saved_models/audio_classification.keras')

start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
 1/12 ━━━━━━━━━━━━━━━━━━━━ 56s 5s/step - accuracy: 0.2812 - loss: 26.1959
Epoch 1: val_loss improved from inf to 10.57680, saving model to saved_models/audio_classification.keras
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - accuracy: 0.4525 - loss: 25.0243 - val_accuracy: 0.8587 - val_loss: 10.5768
Epoch 2/100
 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8438 - loss: 12.5140
Epoch 2: val_loss improved from 10.57680 to 5.22999, saving model to saved_models/audio_classification.keras
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7473 - loss: 15.8942 - val_accuracy: 0.8587 - val_loss: 5.2300
Epoch 3/100
 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 14.9207
Epoch 3: val_loss improved from 5.22999 to 3.21582, saving model to saved_models/audio_classification.keras
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6317 - loss: 13.5161 - val_accuracy: 0.8587 - val_loss: 3.2158
Epoch 4/100
 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5

In [204]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.8586956262588501


In [205]:
X_test[1]

array([-410.85556 ,   46.24001 ,  -10.46998 ,   -5.892804,  -15.497193,
        -11.711424,  -23.498938,  -12.768632,  -13.778734,   -6.802423,
        -14.231   ,  -14.329665,  -16.73    ], dtype=float32)

In [206]:
import numpy as np
predictions = model.predict(X_test)
# Convert probabilities to class labels
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [207]:
import pickle
from sklearn.preprocessing import LabelEncoder

def load_label_encoder(file_path):
    with open(file_path, 'rb') as file:
        classes = pickle.load(file)
    labelencoder = LabelEncoder()
    labelencoder.classes_ = classes
    return labelencoder

def preprocess_audio(filename):
    y, sr = librosa.load(filename, sr=None)
    mfccs_features = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfccs_scaled_features = np.mean(mfccs_features.T, axis=0)
    return mfccs_scaled_features.reshape(1, -1)

def predict_audio_class(filename, model, labelencoder):
    features = preprocess_audio(filename)
    predicted_probabilities = model.predict(features)
    predicted_label = np.argmax(predicted_probabilities, axis=1)
    prediction_class = labelencoder.inverse_transform(predicted_label)
    return prediction_class[0]

if __name__ == "__main__":
    # Load the trained model
    model = tf.keras.models.load_model('saved_models/audio_classification.keras')

    # Load the label encoder
    labelencoder = load_label_encoder('label_classes.pkl')

    # Take user input for the audio file path
    filename = input("Enter the path of the audio file: ")
    
    # Predict the class of the audio file
    predicted_class = predict_audio_class(filename, model, labelencoder)
    print("Predicted class:", predicted_class)

Enter the path of the audio file:  C:\Users\HP\Desktop\baby_crying\donateacry_corpus_cleaned_and_updated_data\belly_pain\ae5f103b-5fee-442f-bb1b-d9d0570c46ab-1431533857965-1.7-m-26-bp.wav


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Predicted class: hungry


In [140]:
# filename = r"C:\Users\HP\Desktop\baby_crying\donateacry_corpus_cleaned_and_updated_data\belly_pain\ae5f103b-5fee-442f-bb1b-d9d0570c46ab-1431533857965-1.7-m-26-bp.wav"
# y, sr = librosa.load(filename, sr=None)
# mfccs_features = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
# mfccs_scaled_features = np.mean(mfccs_features.T, axis=0)

# print("MFCCs scaled features:", mfccs_scaled_features)
# mfccs_scaled_features = mfccs_scaled_features.reshape(1, -1)
# print("Reshaped MFCCs scaled features:", mfccs_scaled_features)
# print("Shape of MFCCs scaled features:", mfccs_scaled_features.shape)

# # Load your trained model
# model = tf.keras.models.load_model('saved_models/audio_classification.keras')

# # Make predictions
# predicted_probabilities = model.predict(mfccs_scaled_features)
# predicted_label = np.argmax(predicted_probabilities, axis=1)
# print("Predicted label (encoded):", predicted_label)

# # Load your label encoder
# labelencoder = LabelEncoder()
# labelencoder.classes_ = np.load('label_classes.npy')

# # Decode the predicted label to get the class name
# prediction_class = labelencoder.inverse_transform(predicted_label)
# print("Predicted class (decoded):", prediction_class)

MFCCs scaled features: [-303.28653     57.470528    -3.8972733   -3.6200895  -22.772476
    2.9935045  -11.351922   -14.612647   -28.033195    -2.375577
  -10.980385     5.6036487    1.424868 ]
Reshaped MFCCs scaled features: [[-303.28653     57.470528    -3.8972733   -3.6200895  -22.772476
     2.9935045  -11.351922   -14.612647   -28.033195    -2.375577
   -10.980385     5.6036487    1.424868 ]]
Shape of MFCCs scaled features: (1, 13)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Predicted label (encoded): [3]
Predicted class (decoded): ['hungry']


In [ ]:
# saved_models/audio_classification.keras

In [137]:
 # label_classes.npy
